# Automatically generated by SST
# pylint: disable=all
from typing import Any

class Resource:
    class Api:
        type: str
        url: str
    class ApiFn:
        name: str
        type: str
        url: str
    class App:
        name: str
        stage: str
    class MyBucket:
        name: str
        type: str
    class Urls:
        api: str
        auth: str
        openapi: str
        site: str
        type: str
    class WWW:
        type: str
        url: str

