packages:
  - packages/*

catalog:
  '@openai/agents': ^0.3.4
  '@orpc/client': ^1.12.2
  '@orpc/openapi': ^1.12.2
  '@orpc/server': ^1.12.2
  '@orpc/zod': ^1.12.2
  '@types/react': 19.2.7
  '@types/react-dom': 19.2.3
  '@workos-inc/node': ^7.77.0
  agents: ^0.2.31
  ai: 5.0.112
  cloudflare: 5.2.0
  drizzle-orm: 0.45.1
  hono: 4.10.8
  immer: 11.0.1
  lucide-react: 0.560.0
  react: 19.2.3
  react-dom: 19.2.3
  vite: 7.2.7
  wrangler: 4.54.0
  zod: 4.1.13

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - aws-sdk
  - sharp
  - esbuild
  - lefthook
  - workerd
