packages:
  - packages/*

catalog:
  '@orpc/client': ^1.11.3
  '@orpc/openapi': ^1.11.3
  '@orpc/server': ^1.11.3
  '@orpc/zod': ^1.11.3
  '@types/react': 19.1.10
  '@types/react-dom': 19.1.7
  '@workos-inc/node': ^7.66.0
  agents: ^0.2.24
  ai: ^5.0.102
  cloudflare: ^5.0.0
  drizzle-orm: ^0.44.7
  hono: ^4.10.7
  react: 19.1.1
  react-dom: 19.1.1
  vite: ^7.2.4
  wrangler: 4.51.0
  zod: 4.1.0

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - aws-sdk
  - sharp
  - esbuild
  - lefthook
  - workerd
