/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.Router"
      "url": string
    }
    "ApiFn": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Bus": {
      "arn": string
      "name": string
      "type": "sst.aws.Bus"
    }
    "Database": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.sst.Linkable"
      "username": string
    }
    "FACEBOOK_APP_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FACEBOOK_APP_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FACEBOOK_REDIRECT_URI": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Storage": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Urls": {
      "api": string
      "auth": string
      "openapi": string
      "site": string
      "type": "sst.sst.Linkable"
    }
    "Worker": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}