/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkspacesRouteRouteImport } from './routes/_authenticated/workspaces/route'
import { Route as AuthenticatedWorkspacesIndexRouteImport } from './routes/_authenticated/workspaces/index'
import { Route as AuthenticatedWorkspacesWorkspaceSlugRouteRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/route'
import { Route as AuthenticatedWorkspacesWorkspaceSlugIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/index'
import { Route as AuthenticatedWorkspacesWorkspaceSlugInboxRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/inbox'
import { Route as AuthenticatedWorkspacesWorkspaceSlugConnectedAccountsRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/connected-accounts'
import { Route as AuthenticatedWorkspacesWorkspaceSlugComposerRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/composer'
import { Route as AuthenticatedWorkspacesWorkspaceSlugCalendarRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/calendar'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspacesRouteRoute =
  AuthenticatedWorkspacesRouteRouteImport.update({
    id: '/workspaces',
    path: '/workspaces',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspacesIndexRoute =
  AuthenticatedWorkspacesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugRouteRoute =
  AuthenticatedWorkspacesWorkspaceSlugRouteRouteImport.update({
    id: '/$workspaceSlug',
    path: '/$workspaceSlug',
    getParentRoute: () => AuthenticatedWorkspacesRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugIndexRoute =
  AuthenticatedWorkspacesWorkspaceSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugInboxRoute =
  AuthenticatedWorkspacesWorkspaceSlugInboxRouteImport.update({
    id: '/inbox',
    path: '/inbox',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugConnectedAccountsRoute =
  AuthenticatedWorkspacesWorkspaceSlugConnectedAccountsRouteImport.update({
    id: '/connected-accounts',
    path: '/connected-accounts',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugComposerRoute =
  AuthenticatedWorkspacesWorkspaceSlugComposerRouteImport.update({
    id: '/composer',
    path: '/composer',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugCalendarRoute =
  AuthenticatedWorkspacesWorkspaceSlugCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/workspaces': typeof AuthenticatedWorkspacesRouteRouteWithChildren
  '/workspaces/$workspaceSlug': typeof AuthenticatedWorkspacesWorkspaceSlugRouteRouteWithChildren
  '/workspaces/': typeof AuthenticatedWorkspacesIndexRoute
  '/workspaces/$workspaceSlug/calendar': typeof AuthenticatedWorkspacesWorkspaceSlugCalendarRoute
  '/workspaces/$workspaceSlug/composer': typeof AuthenticatedWorkspacesWorkspaceSlugComposerRoute
  '/workspaces/$workspaceSlug/connected-accounts': typeof AuthenticatedWorkspacesWorkspaceSlugConnectedAccountsRoute
  '/workspaces/$workspaceSlug/inbox': typeof AuthenticatedWorkspacesWorkspaceSlugInboxRoute
  '/workspaces/$workspaceSlug/': typeof AuthenticatedWorkspacesWorkspaceSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/workspaces': typeof AuthenticatedWorkspacesIndexRoute
  '/workspaces/$workspaceSlug/calendar': typeof AuthenticatedWorkspacesWorkspaceSlugCalendarRoute
  '/workspaces/$workspaceSlug/composer': typeof AuthenticatedWorkspacesWorkspaceSlugComposerRoute
  '/workspaces/$workspaceSlug/connected-accounts': typeof AuthenticatedWorkspacesWorkspaceSlugConnectedAccountsRoute
  '/workspaces/$workspaceSlug/inbox': typeof AuthenticatedWorkspacesWorkspaceSlugInboxRoute
  '/workspaces/$workspaceSlug': typeof AuthenticatedWorkspacesWorkspaceSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/workspaces': typeof AuthenticatedWorkspacesRouteRouteWithChildren
  '/_authenticated/workspaces/$workspaceSlug': typeof AuthenticatedWorkspacesWorkspaceSlugRouteRouteWithChildren
  '/_authenticated/workspaces/': typeof AuthenticatedWorkspacesIndexRoute
  '/_authenticated/workspaces/$workspaceSlug/calendar': typeof AuthenticatedWorkspacesWorkspaceSlugCalendarRoute
  '/_authenticated/workspaces/$workspaceSlug/composer': typeof AuthenticatedWorkspacesWorkspaceSlugComposerRoute
  '/_authenticated/workspaces/$workspaceSlug/connected-accounts': typeof AuthenticatedWorkspacesWorkspaceSlugConnectedAccountsRoute
  '/_authenticated/workspaces/$workspaceSlug/inbox': typeof AuthenticatedWorkspacesWorkspaceSlugInboxRoute
  '/_authenticated/workspaces/$workspaceSlug/': typeof AuthenticatedWorkspacesWorkspaceSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/workspaces'
    | '/workspaces/$workspaceSlug'
    | '/workspaces/'
    | '/workspaces/$workspaceSlug/calendar'
    | '/workspaces/$workspaceSlug/composer'
    | '/workspaces/$workspaceSlug/connected-accounts'
    | '/workspaces/$workspaceSlug/inbox'
    | '/workspaces/$workspaceSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/workspaces'
    | '/workspaces/$workspaceSlug/calendar'
    | '/workspaces/$workspaceSlug/composer'
    | '/workspaces/$workspaceSlug/connected-accounts'
    | '/workspaces/$workspaceSlug/inbox'
    | '/workspaces/$workspaceSlug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/_authenticated/workspaces'
    | '/_authenticated/workspaces/$workspaceSlug'
    | '/_authenticated/workspaces/'
    | '/_authenticated/workspaces/$workspaceSlug/calendar'
    | '/_authenticated/workspaces/$workspaceSlug/composer'
    | '/_authenticated/workspaces/$workspaceSlug/connected-accounts'
    | '/_authenticated/workspaces/$workspaceSlug/inbox'
    | '/_authenticated/workspaces/$workspaceSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspaces': {
      id: '/_authenticated/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AuthenticatedWorkspacesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspaces/': {
      id: '/_authenticated/workspaces/'
      path: '/'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof AuthenticatedWorkspacesIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug': {
      id: '/_authenticated/workspaces/$workspaceSlug'
      path: '/$workspaceSlug'
      fullPath: '/workspaces/$workspaceSlug'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRouteImport
      parentRoute: typeof AuthenticatedWorkspacesRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/': {
      id: '/_authenticated/workspaces/$workspaceSlug/'
      path: '/'
      fullPath: '/workspaces/$workspaceSlug/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/inbox': {
      id: '/_authenticated/workspaces/$workspaceSlug/inbox'
      path: '/inbox'
      fullPath: '/workspaces/$workspaceSlug/inbox'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugInboxRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/connected-accounts': {
      id: '/_authenticated/workspaces/$workspaceSlug/connected-accounts'
      path: '/connected-accounts'
      fullPath: '/workspaces/$workspaceSlug/connected-accounts'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugConnectedAccountsRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/composer': {
      id: '/_authenticated/workspaces/$workspaceSlug/composer'
      path: '/composer'
      fullPath: '/workspaces/$workspaceSlug/composer'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugComposerRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/calendar': {
      id: '/_authenticated/workspaces/$workspaceSlug/calendar'
      path: '/calendar'
      fullPath: '/workspaces/$workspaceSlug/calendar'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugCalendarRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRoute
    }
  }
}

interface AuthenticatedWorkspacesWorkspaceSlugRouteRouteChildren {
  AuthenticatedWorkspacesWorkspaceSlugCalendarRoute: typeof AuthenticatedWorkspacesWorkspaceSlugCalendarRoute
  AuthenticatedWorkspacesWorkspaceSlugComposerRoute: typeof AuthenticatedWorkspacesWorkspaceSlugComposerRoute
  AuthenticatedWorkspacesWorkspaceSlugConnectedAccountsRoute: typeof AuthenticatedWorkspacesWorkspaceSlugConnectedAccountsRoute
  AuthenticatedWorkspacesWorkspaceSlugInboxRoute: typeof AuthenticatedWorkspacesWorkspaceSlugInboxRoute
  AuthenticatedWorkspacesWorkspaceSlugIndexRoute: typeof AuthenticatedWorkspacesWorkspaceSlugIndexRoute
}

const AuthenticatedWorkspacesWorkspaceSlugRouteRouteChildren: AuthenticatedWorkspacesWorkspaceSlugRouteRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceSlugCalendarRoute:
      AuthenticatedWorkspacesWorkspaceSlugCalendarRoute,
    AuthenticatedWorkspacesWorkspaceSlugComposerRoute:
      AuthenticatedWorkspacesWorkspaceSlugComposerRoute,
    AuthenticatedWorkspacesWorkspaceSlugConnectedAccountsRoute:
      AuthenticatedWorkspacesWorkspaceSlugConnectedAccountsRoute,
    AuthenticatedWorkspacesWorkspaceSlugInboxRoute:
      AuthenticatedWorkspacesWorkspaceSlugInboxRoute,
    AuthenticatedWorkspacesWorkspaceSlugIndexRoute:
      AuthenticatedWorkspacesWorkspaceSlugIndexRoute,
  }

const AuthenticatedWorkspacesWorkspaceSlugRouteRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceSlugRouteRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceSlugRouteRouteChildren,
  )

interface AuthenticatedWorkspacesRouteRouteChildren {
  AuthenticatedWorkspacesWorkspaceSlugRouteRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRouteWithChildren
  AuthenticatedWorkspacesIndexRoute: typeof AuthenticatedWorkspacesIndexRoute
}

const AuthenticatedWorkspacesRouteRouteChildren: AuthenticatedWorkspacesRouteRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceSlugRouteRoute:
      AuthenticatedWorkspacesWorkspaceSlugRouteRouteWithChildren,
    AuthenticatedWorkspacesIndexRoute: AuthenticatedWorkspacesIndexRoute,
  }

const AuthenticatedWorkspacesRouteRouteWithChildren =
  AuthenticatedWorkspacesRouteRoute._addFileChildren(
    AuthenticatedWorkspacesRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedWorkspacesRouteRoute: typeof AuthenticatedWorkspacesRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedWorkspacesRouteRoute:
    AuthenticatedWorkspacesRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
