import { Container } from "@cloudflare/containers";
import type { Client } from "@connectrpc/connect";
import { createClient } from "@connectrpc/connect";
import { createConnectTransport } from "@connectrpc/connect-web";
import {
  type BurnSubtitleRequest,
  type BurnSubtitleResponse,
  ContainerService,
  type ExtractFramesRequest,
  type ExtractFramesResponse,
  type PingResponse,
  type ResizeVideoRequest,
  type ResizeVideoResponse,
  type RunFfmpegRequest,
  type RunFfmpegResponse,
  type TranscodeVideoRequest,
  type TranscodeVideoResponse,
} from "./containers/gen/containers/v1/container_pb";

/**
 * our Golang container backend. lightweight processor that has ffmpeg, r2 mounted via FUSE,
 * and can be extended to other tasks. type safe RPC via connect-rpc.
 */
export class ContainerBackend extends Container {
  defaultPort = 8080;
  requiredPorts = [8080];
  sleepAfter = "60s";
  envVars = {
    MESSAGE: "I was passed in via the container class!",
    ...process.env,
  };

  override onStart() {
    console.log("Container successfully started");
  }

  override onStop() {
    console.log("Container successfully shut down");
  }

  override onError(error: unknown) {
    console.log("Container error:", JSON.stringify(error));
  }
  /**
   * RPC calls via connect-rpc to our go backend
   */
  async ping(): Promise<PingResponse> {
    const c = await this.getClient();
    return await c.ping({});
  }

  private client?: Client<typeof ContainerService>;

  private async getClient() {
    if (!this.client) {
      const transport = createConnectTransport({
        baseUrl: "http://localhost:8080",
        // Worker fetch is provided by the container runtime
        fetch: (input, init) =>
          this.containerFetch(input, {
            ...init,
            redirect: "manual",
          }),
        useBinaryFormat: false,
      });
      this.client = createClient(ContainerService, transport);
    }
    await this.startAndWaitForPorts(this.defaultPort);
    return this.client;
  }

  async resizeVideo(
    req: Omit<ResizeVideoRequest, "$typeName">,
  ): Promise<ResizeVideoResponse> {
    const client = await this.getClient();
    return await client.resizeVideo({
      ...req,
      $typeName: "containers.v1.ResizeVideoRequest", // optional
    });
  }

  async runFfmpeg(
    req: Omit<RunFfmpegRequest, "$typeName">,
  ): Promise<RunFfmpegResponse> {
    const client = await this.getClient();
    return await client.runFfmpeg({
      ...req,
      $typeName: "containers.v1.RunFfmpegRequest", // optional
    });
  }

  async probeMedia(url: string) {
    const client = await this.getClient();
    return await client.probeMedia({ url });
  }

  async transcodeVideo(
    req: Omit<TranscodeVideoRequest, "$typeName">,
  ): Promise<TranscodeVideoResponse> {
    const client = await this.getClient();
    return await client.transcodeVideo({
      ...req,
      $typeName: "containers.v1.TranscodeVideoRequest",
    });
  }

  /**
   * Burn ASS subtitles into a video
   * @param req.videoUrl - URL of the input video
   * @param req.assContent - ASS subtitle file content (generated by viral-subtitle module)
   * @returns Output video URL with burned-in subtitles
   */
  async burnSubtitle(
    req: Omit<BurnSubtitleRequest, "$typeName">,
  ): Promise<BurnSubtitleResponse> {
    const client = await this.getClient();
    return await client.burnSubtitle({
      ...req,
      $typeName: "containers.v1.BurnSubtitleRequest",
    });
  }

  /**
   * Extract one or more frames from a video as JPEG images
   * @param req.videoUrl - URL of the input video
   * @param req.timestamps - Timestamps in seconds to extract (default: [0.5])
   * @param req.frameCount - Alternative: extract N frames evenly distributed (overrides timestamps)
   * @param req.outputPrefix - R2 path prefix for output files
   * @param req.outputFilename - Custom filename for single frame (default: "frame_0.jpg")
   * @param req.bucket - Target R2 bucket (default, reference, or public)
   * @param req.quality - JPEG quality 1-31, lower is better (default: 2)
   * @returns Array of extracted frames with R2 URLs and dimensions
   */
  async extractFrames(
    req: Omit<ExtractFramesRequest, "$typeName">,
  ): Promise<ExtractFramesResponse> {
    const client = await this.getClient();
    return await client.extractFrames({
      ...req,
      $typeName: "containers.v1.ExtractFramesRequest",
    });
  }
}

// Re-export Platform and R2Bucket enums for use in workflows
export {
  Platform,
  R2Bucket,
} from "./containers/gen/containers/v1/container_pb";
