name: "Setup Node.js with pnpm"
description: "Setup Node.js, pnpm, and install dependencies"
runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: "pnpm"

    - name: Install dependencies
      run: pnpm install
      shell: bash
