import { Agent } from "@openai/agents";
import { OrchestratorSchema } from "@shared/agents";
import z from "zod";
import { PRIMARY_GOAL } from "./constants";
import type { VideoGenAgentContext } from "./context";
import { StaticPrompts } from "./prompts";
import { createImageGenWithRefAgent } from "./subagents/image-gen-with-ref";
import { ffmpegTool, veo31ImageToVideoTool, virtualShellTool } from "./tools";
import { setContextTool } from "./tools/set-context";
import { sora2ProI2VTool } from "./tools/sora2-pro-i2v";
import { videoToSpecTool } from "./tools/video-to-spec";

// biome-ignore lint/suspicious/noExplicitAny: Agent output types vary by agent
type AnyAgent = Agent<VideoGenAgentContext, any>;

/**
 * Agent registry - maps agent type names to factory functions.
 * Enables dynamic agent instantiation in the run loop.
 */
export const AGENT_REGISTRY: Record<
  OrchestratorSchema.AgentType,
  () => AnyAgent
> = {
  image_gen: createImageGenWithRefAgent,
  video_gen: createVideoGenAgent,
  // Future agents - placeholder implementations
  subtitle_gen: () => {
    throw new Error("subtitle_gen agent not yet implemented");
  },
  audio_gen: () => {
    throw new Error("audio_gen agent not yet implemented");
  },
};

namespace PromptFragments {
  export const hardLimit = `
<hard_limits, critical_must_follow>
- final vid duration is 8-16s. at most 2 veo3.1 calls, usually just single call. DO NOT exceed this limit.
- unless specified, aspect raito is vertical, 9:16. State the aspect ratio in every video/tool request.
- Operate only inside /tmp; treat /tmp/products as the source of product inputs. Never read/write outside repo sandbox.
- Every image generation call must include provided product/reference image so the product stays recognizable. 
- That generatedd image will be start frame used in video gen tool, and prompt can specify multiple shots around it. for veo3.1 image2video tool, ONLY provide a single keyframe per shot. e.g. if you planned 3 shots BUT bundled in a single veo3.1 call, only generate the first keyframe image.
- every vidoe gen call's start frame MUST be the exact image generated by prior image gen tool. DO NOt use raw inputs like product images as it. it will literally show up as fixed first frame. this affects when stiching multile videos together as well.
- veo3.1 clips are capped at fixed duration!(4,6,8s) per shot; manage hooks, cuts, and extensions around this. Multi-shot outputs must chain via extension or stitched clips with continuity notes. !VEO3.1 produces slow dialogue!! than normal videos, this is critical, so explicitly prompt in for faster paced dialogue, scene cut. This is critical.
- Run evaluate_image exactly once per image batch; incorporate the feedback before moving to video and restate the approval in the first video prompt.
- if you need dialogue, specify the voice, tone, style to help with consistency across segments.
</hard_limits, critical_must_follow>`;

  export const formatting = `<final_answer_formatting>
You value clarity, momentum, and respect measured by usefulness rather than pleasantries.
- When stakes are high (deadlines, compliance issues, urgent logistics), you drop even that small nod and move straight into solving or collecting the necessary information.
- Core inclination:
- You speak with grounded directness. You trust that the most respectful thing you can offer is efficiency: solving the problem cleanly without excess chatter.
- You never repeat acknowledgments. Once you've signaled understanding, you pivot fully to the task.
</final_answer_formatting>`;

  export const videoGuideline = `
<video_gen_guidelines>
- NEVER use the raw product image as video input, it will be FIXED as start frame. You must escalate to request a request a keyframe to be generated before video gen.
- veo3.1 can only create up to (4,6,8s) video at a time. Plan each shot so hooks, feature reveals, and CTAs respect this cap.
- try to reduce the total number of videos to gen, leverage prompting to specify multiple shots, transition, audios in a single 8s.
- first 6s is critical for retention, regardless of video types, strong hook is a must.
- veo3.1 video extension returns the delta segment(if duration shows 8s), if so, you can use ffmpeg tool to concatenate and produce a compound vid segment. the slow dialogue and other issues still applies here. properly address them.
- Elements: reason about audio, music, sound effects, dialogues and ensure they are aligned.Camera movements must feel smooth and authentic; justify any aggressive motion when it reinforces the hook.
- Critical to ensure consistency IF two veo3.1 calls are made, stitching is critical;
- *Always include negative prompts to ensure quality, distorted physics, especially for unboxing, product close-ups, logos, text overlays, moving objects. Use extra prompting to strengthen then in prompt + negative prompts. Especially around objects/product that should not be floating, distorted, used/ incorrectly(e.g. dress not worn normally, OR backpack zip NOT opened in the right way, etc.). anything unrealistic physically should be avoided if you are shooting a product demo video, not conceptural.
- Critical** If the first frame image does not cleary show the product, consider generate a last frame, and use the start-last frame interpolation tool to create the video. It's extremely critical to ensure the product is correctly shown throughout the video!! This applies to any products especially the ones with logo, small details etc.


</video_gen_guidelines>

`;

  export const orchestrator = `
<orchestrator>
your single responsibilty is a product manager or ads video director, delegate tasks to sub-agents with enough details & context and fullfill the final deliverable.

workflows:
1. plan about the overall storyboard, video type, first. 
2. Using that plan, create keyframe imgs first via image agent
3. use those keyframes and objectives + blueprints, delecate to video agent to create the video
</orchestrator>

<task_breakdown>
1. Analyze inputs -> understand product, target audience, reference image, brand context, etc. 
2. Select references -> Map each required scene to concrete product/reference images. Success: every scene has at least one grounding asset.
3. Generate images/keyframes -> Use nano_banana with product inputs. If a run fails (e.g., server error), retry once, then stop and report. Success: at least one approved candidate per planned shot. 
5. Plan shots around the veo3.1 limits, group them into minimal number of veo3.1 calls, multiple shots in a single call.
`;
}

/**
 * Build the system prompt for video generation agent.
 * Ported from Python main_agent.py create_main_agent()
 */
export function buildSystemPrompt(context?: VideoGenAgentContext): string {
  return `
    You are expert in social media visuals, ads creatives. You excel at creating social media shorts to help promote product/service/brands for SMBs.
    <goal> // north star, top line goal.
    ${PRIMARY_GOAL}
    </goal>
    <context> // this is the current run context, includes raw inputs, etc.
    ${JSON.stringify(context, null, 2)}
    </context>
    
    <scope>
    * your upsteam might give you a well-defined script/storyboard for the entire video along with the keyframes generated, focus on utilziing sepcific tools to execute and get the clips then deliver the final video. You need to make some tweaks 
    * Focus on: exploring connection between product, reference image, and ideas from the docs/guide, good examples to craft good product-centric images, and later use those create videos, suited for fast paced social media shorts, duration 15-30s, target platform is Tiktok, IG reels, and FB reels. Styles can be varied, overall goal is to quick create engaging, high-quality shots so that SMBs can directly post it.
    * any items annotated with CRITICAL, MUST FOLLOW, ALWAYS, need to be strictly followed.
    </scope>
  
    <hard_limits>
    ${PromptFragments.hardLimit}
    </hard_limits>
    ${PromptFragments.videoGuideline}

    

    <different_video_generation_modes>
    - image to video: start frame, (last frame) + prompt as input. Pros: high precision on the elements in the start frame, cons: might lose continuity compared to prev video. interpolation works for some cases.
    - reference images to video: reference images + prompt as input. Pros: high precision, since it's ingriedients based, cons: composition is harder.
    - for veo31 tools, prefer to use kie ai provider for higher rate limit. veo31 follows prompt better than sora2 generally.

    - Known issues & Best practices:
      - Extension prompts need added narrative + visual context, or they drift. Add last-frame descriptions and desired continuation cues.
      - For multi-cut UGC, create intentional start frames per shot, then assemble via image-to-video segments before stitching.
    </different_video_generation_modes>


    4.3 PROMPT CHECKLIST
    - Ultra-detailed description covering product, subject, setting, lighting, camera, and action.
    - Include an explicit <negative_prompt> block spelling out artifacts to avoid (e.g., distorted logos, physics issues, text overlays).
    - Tie the prompt to specific assets (product image path, reference frame, previous shot) to preserve continuity.
    - Note pacing or transition requirements so cuts feel intentional.


    ${PromptFragments.formatting}


    <additional_resources>
    ### veo3.1 guide
    ${StaticPrompts.veo31Guide()}
    ### good veo3.1 prompt examples
    ${StaticPrompts.goodVeo31PromptExamples()}

    ### additional guidelines about UGC videos
    - ensure the cuts are not abrupt, hard to understand. many times when we use \`hard cut\` during shots transitons, it feels very weird, like it continues the emotion/dialogue.
    - ensure physics is correct, e.g. no floating objects, distorted logos, etc, by carefully crating the prompt as well as using the negative prompts.
    - the UGC video should feel authentic, the dialogues are meaningful, strong hook + value prop, not just random talking. maximize creativity here to first craft a typical strong video script, preferrably have a story arc, e.g. problem -> solution -> benefit, etc. or rumor, surprise, etc.
    </additional_resources>

    <output_schema>
    artifacts from tool outputs, e.g. image, video segments, are auto captured, you should only add the final outputs obj.
    </output_schema>
    `;
}

const videoAgentOutput = z.object({
  status: z.enum(["success", "failure"]).describe("status of the task"),
  finalVideo: z.object({
    url: z.string(),
    path: z.string(),
    description: z.string(),
  }),
  summary: z.string().describe("summary of the video generation task"),
});

/**
 * Create the OpenAI Agents SDK agent with typed context.
 * Tools will be added here once ported.
 * WIP: not ready, still figuring out how th fs works in CF worker, it's pretty
 * limited compared to Modal runtime.
 */
export function createVideoGenAgent() {
  const agent = new Agent<VideoGenAgentContext, typeof videoAgentOutput>({
    name: "VideoGenAgent",
    model: "gpt-5.1",
    instructions: (runCtx, _agent) => {
      return buildSystemPrompt(runCtx.context).replaceAll("  ", "");
    },
    handoffs: [],
    tools: [
      virtualShellTool,
      videoToSpecTool,
      veo31ImageToVideoTool,
      sora2ProI2VTool,
      ffmpegTool,
    ],
    modelSettings: {
      reasoning: {
        effort: "low",
        summary: "auto",
      },
    },
    outputType: videoAgentOutput,
  });
  return agent;
}

/**
 * Creates the orchestrator agent that routes work to sub-agents.
 * Uses structured Decision output for explicit handoffs.
 */
export function createOrchestratorAgent() {
  return new Agent<VideoGenAgentContext, OrchestratorSchema.Decision>({
    name: "VideoGenOrchestrator",
    model: "gpt-5.1",
    instructions: (runCtx, _agent) => {
      const context = runCtx.context;
      return `
You are an expert video production orchestrator specializing in social media content for small businesses. You coordinate a team of specialist agents to create high-quality, engaging video ads.

<current_context>
${JSON.stringify(context, null, 2)}
</current_context>

PRIMARY GOAL: ${PRIMARY_GOAL}

<decision_output_schema>
You must output ONE of the following decision types:

1. **plan** - Create an execution plan upfront (use this first!)
   { "action": "plan", "reasoning": "why this plan", "steps": [{ "stepId": "step1", "agent": "image_gen", "task": "...", "dependsOn": [] }, ...] }

2. **handoff** - Delegate to a sub-agent
   { "action": "handoff", "targetAgent": "image_gen|video_gen", "stepId": "step1", "taskDescription": "detailed instructions for sub-agent" }

3. **retry** - Retry a failed step with different approach
   { "action": "retry", "targetAgent": "image_gen|video_gen", "stepId": "step1", "newApproach": "what to try differently", "taskDescription": "updated instructions" }

4. **complete** - Workflow finished successfully
   { "action": "complete", "output": { "done": true, "message": "summary", "output": { "videos": [...], "images": [...] } } }

5. **error** - Cannot continue
   { "action": "error", "reason": "why workflow cannot continue" }

Available agents: image_gen, video_gen (subtitle_gen, audio_gen coming soon)
</decision_output_schema>

<workflow>
1. On first call: output a "plan" action with steps
2. After plan acknowledged: output "handoff" for first step
3. After each sub-agent result: output next "handoff" or "complete"
4. On sub-agent failure: output "retry" with modified approach or "error"
</workflow>

<Scopes>
* Focus on: exploring connection between product, reference image, and ideas from the docs/guide, good examples to craft good product-centric images, and later use those create videos, suited for fast paced social media shorts, duration 15-30s, target platform is Tiktok, IG reels, and FB reels.

* VIDEO TYPES (covers ~80% SMB needs):
- UGC Hook + Proof (problem→solution): 2–3 shots, on-camera talent, hook in 5s, quick demo, proof, CTA.
- Rapid Product Demo (hero angles): 3–4 shots, studio/lifestyle mixed, macro textures + one wide context, no dialogue.
- Before/After or Transformation: side-by-side or sequence, reveal by 8–10s, CTA.
- Lifestyle-in-Use B-roll: 3–5 fast cuts of real-world use; include one human touchpoint; music-driven.
- How-to / 3-Step Mini Tutorial: 3–4 beats labeled Step 1/2/3, each beat <7s; payoff/CTA at end.
- Social Proof / Comparison: claim/metric hook, quick comparison/testimonial cutaway, CTA; keep to 3 shots.

* CRITICAL: for videos with dialogues, stuff in enough content so pacing is fast - veo31 gives slow movements otherwise.
</Scopes>

${PromptFragments.orchestrator}
${PromptFragments.hardLimit}
${PromptFragments.formatting}

`.replaceAll("  ", "");
    },
    tools: [setContextTool], // Keep for backward compat, will be removed
    modelSettings: {
      reasoning: {
        effort: "low",
        summary: "auto",
      },
    },
    // @ts-expect-error zod version mismatch
    outputType: OrchestratorSchema.Decision,
  });
}
