# Automatically generated by SST
# pylint: disable=all
from typing import Any

class Resource:
    class Api:
        type: str
        url: str
    class ApiFn:
        name: str
        type: str
        url: str
    class App:
        name: str
        stage: str
    class Bus:
        arn: str
        name: str
        type: str
    class Database:
        database: str
        host: str
        password: str
        port: float
        type: str
        username: str
    class FACEBOOK_APP_ID:
        type: str
        value: str
    class FACEBOOK_APP_SECRET:
        type: str
        value: str
    class FACEBOOK_REDIRECT_URI:
        type: str
        value: str
    class Storage:
        name: str
        type: str
    class Urls:
        api: str
        auth: str
        openapi: str
        site: str
        type: str
    class WWW:
        type: str
        url: str
    class WWW_RR:
        type: str
        url: str
    class Worker:
        type: str
        url: str

