/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkspacesRouteRouteImport } from './routes/_authenticated/workspaces/route'
import { Route as AuthenticatedWorkspacesIndexRouteImport } from './routes/_authenticated/workspaces/index'
import { Route as AuthenticatedWorkspacesWorkspaceSlugRouteRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/route'
import { Route as AuthenticatedWorkspacesWorkspaceSlugIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/index'
import { Route as AuthenticatedWorkspacesWorkspaceSlugTeamRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/team'
import { Route as AuthenticatedWorkspacesWorkspaceSlugSettingsRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/settings'
import { Route as AuthenticatedWorkspacesWorkspaceSlugProductVisualsRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/product-visuals'
import { Route as AuthenticatedWorkspacesWorkspaceSlugInsightsRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/insights'
import { Route as AuthenticatedWorkspacesWorkspaceSlugInboxRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/inbox'
import { Route as AuthenticatedWorkspacesWorkspaceSlugContentRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/content'
import { Route as AuthenticatedWorkspacesWorkspaceSlugComposerRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/composer'
import { Route as AuthenticatedWorkspacesWorkspaceSlugCalendarRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/calendar'
import { Route as AuthenticatedWorkspacesWorkspaceSlugLabsRouteRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/labs/route'
import { Route as AuthenticatedWorkspacesWorkspaceSlugStylesIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/styles/index'
import { Route as AuthenticatedWorkspacesWorkspaceSlugProductsIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/products/index'
import { Route as AuthenticatedWorkspacesWorkspaceSlugProductVisualsV2IndexRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/product-visuals-v2/index'
import { Route as AuthenticatedWorkspacesWorkspaceSlugInboxIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/inbox/index'
import { Route as AuthenticatedWorkspacesWorkspaceSlugProductsProductIdRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/products/$productId'
import { Route as AuthenticatedWorkspacesWorkspaceSlugLabsPlaygroundRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/labs/playground'
import { Route as AuthenticatedWorkspacesWorkspaceSlugLabsApiTestingRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/labs/api-testing'
import { Route as AuthenticatedWorkspacesWorkspaceSlugInboxConversationIdRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/inbox/$conversationId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspacesRouteRoute =
  AuthenticatedWorkspacesRouteRouteImport.update({
    id: '/workspaces',
    path: '/workspaces',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspacesIndexRoute =
  AuthenticatedWorkspacesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugRouteRoute =
  AuthenticatedWorkspacesWorkspaceSlugRouteRouteImport.update({
    id: '/$workspaceSlug',
    path: '/$workspaceSlug',
    getParentRoute: () => AuthenticatedWorkspacesRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugIndexRoute =
  AuthenticatedWorkspacesWorkspaceSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugTeamRoute =
  AuthenticatedWorkspacesWorkspaceSlugTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugSettingsRoute =
  AuthenticatedWorkspacesWorkspaceSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugProductVisualsRoute =
  AuthenticatedWorkspacesWorkspaceSlugProductVisualsRouteImport.update({
    id: '/product-visuals',
    path: '/product-visuals',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugInsightsRoute =
  AuthenticatedWorkspacesWorkspaceSlugInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugInboxRoute =
  AuthenticatedWorkspacesWorkspaceSlugInboxRouteImport.update({
    id: '/inbox',
    path: '/inbox',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugContentRoute =
  AuthenticatedWorkspacesWorkspaceSlugContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugComposerRoute =
  AuthenticatedWorkspacesWorkspaceSlugComposerRouteImport.update({
    id: '/composer',
    path: '/composer',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugCalendarRoute =
  AuthenticatedWorkspacesWorkspaceSlugCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugLabsRouteRoute =
  AuthenticatedWorkspacesWorkspaceSlugLabsRouteRouteImport.update({
    id: '/labs',
    path: '/labs',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugStylesIndexRoute =
  AuthenticatedWorkspacesWorkspaceSlugStylesIndexRouteImport.update({
    id: '/styles/',
    path: '/styles/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugProductsIndexRoute =
  AuthenticatedWorkspacesWorkspaceSlugProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugProductVisualsV2IndexRoute =
  AuthenticatedWorkspacesWorkspaceSlugProductVisualsV2IndexRouteImport.update({
    id: '/product-visuals-v2/',
    path: '/product-visuals-v2/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugInboxIndexRoute =
  AuthenticatedWorkspacesWorkspaceSlugInboxIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugInboxRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugProductsProductIdRoute =
  AuthenticatedWorkspacesWorkspaceSlugProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugLabsPlaygroundRoute =
  AuthenticatedWorkspacesWorkspaceSlugLabsPlaygroundRouteImport.update({
    id: '/playground',
    path: '/playground',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugLabsRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugLabsApiTestingRoute =
  AuthenticatedWorkspacesWorkspaceSlugLabsApiTestingRouteImport.update({
    id: '/api-testing',
    path: '/api-testing',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugLabsRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugInboxConversationIdRoute =
  AuthenticatedWorkspacesWorkspaceSlugInboxConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugInboxRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/workspaces': typeof AuthenticatedWorkspacesRouteRouteWithChildren
  '/workspaces/$workspaceSlug': typeof AuthenticatedWorkspacesWorkspaceSlugRouteRouteWithChildren
  '/workspaces/': typeof AuthenticatedWorkspacesIndexRoute
  '/workspaces/$workspaceSlug/labs': typeof AuthenticatedWorkspacesWorkspaceSlugLabsRouteRouteWithChildren
  '/workspaces/$workspaceSlug/calendar': typeof AuthenticatedWorkspacesWorkspaceSlugCalendarRoute
  '/workspaces/$workspaceSlug/composer': typeof AuthenticatedWorkspacesWorkspaceSlugComposerRoute
  '/workspaces/$workspaceSlug/content': typeof AuthenticatedWorkspacesWorkspaceSlugContentRoute
  '/workspaces/$workspaceSlug/inbox': typeof AuthenticatedWorkspacesWorkspaceSlugInboxRouteWithChildren
  '/workspaces/$workspaceSlug/insights': typeof AuthenticatedWorkspacesWorkspaceSlugInsightsRoute
  '/workspaces/$workspaceSlug/product-visuals': typeof AuthenticatedWorkspacesWorkspaceSlugProductVisualsRoute
  '/workspaces/$workspaceSlug/settings': typeof AuthenticatedWorkspacesWorkspaceSlugSettingsRoute
  '/workspaces/$workspaceSlug/team': typeof AuthenticatedWorkspacesWorkspaceSlugTeamRoute
  '/workspaces/$workspaceSlug/': typeof AuthenticatedWorkspacesWorkspaceSlugIndexRoute
  '/workspaces/$workspaceSlug/inbox/$conversationId': typeof AuthenticatedWorkspacesWorkspaceSlugInboxConversationIdRoute
  '/workspaces/$workspaceSlug/labs/api-testing': typeof AuthenticatedWorkspacesWorkspaceSlugLabsApiTestingRoute
  '/workspaces/$workspaceSlug/labs/playground': typeof AuthenticatedWorkspacesWorkspaceSlugLabsPlaygroundRoute
  '/workspaces/$workspaceSlug/products/$productId': typeof AuthenticatedWorkspacesWorkspaceSlugProductsProductIdRoute
  '/workspaces/$workspaceSlug/inbox/': typeof AuthenticatedWorkspacesWorkspaceSlugInboxIndexRoute
  '/workspaces/$workspaceSlug/product-visuals-v2': typeof AuthenticatedWorkspacesWorkspaceSlugProductVisualsV2IndexRoute
  '/workspaces/$workspaceSlug/products': typeof AuthenticatedWorkspacesWorkspaceSlugProductsIndexRoute
  '/workspaces/$workspaceSlug/styles': typeof AuthenticatedWorkspacesWorkspaceSlugStylesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/workspaces': typeof AuthenticatedWorkspacesIndexRoute
  '/workspaces/$workspaceSlug/labs': typeof AuthenticatedWorkspacesWorkspaceSlugLabsRouteRouteWithChildren
  '/workspaces/$workspaceSlug/calendar': typeof AuthenticatedWorkspacesWorkspaceSlugCalendarRoute
  '/workspaces/$workspaceSlug/composer': typeof AuthenticatedWorkspacesWorkspaceSlugComposerRoute
  '/workspaces/$workspaceSlug/content': typeof AuthenticatedWorkspacesWorkspaceSlugContentRoute
  '/workspaces/$workspaceSlug/insights': typeof AuthenticatedWorkspacesWorkspaceSlugInsightsRoute
  '/workspaces/$workspaceSlug/product-visuals': typeof AuthenticatedWorkspacesWorkspaceSlugProductVisualsRoute
  '/workspaces/$workspaceSlug/settings': typeof AuthenticatedWorkspacesWorkspaceSlugSettingsRoute
  '/workspaces/$workspaceSlug/team': typeof AuthenticatedWorkspacesWorkspaceSlugTeamRoute
  '/workspaces/$workspaceSlug': typeof AuthenticatedWorkspacesWorkspaceSlugIndexRoute
  '/workspaces/$workspaceSlug/inbox/$conversationId': typeof AuthenticatedWorkspacesWorkspaceSlugInboxConversationIdRoute
  '/workspaces/$workspaceSlug/labs/api-testing': typeof AuthenticatedWorkspacesWorkspaceSlugLabsApiTestingRoute
  '/workspaces/$workspaceSlug/labs/playground': typeof AuthenticatedWorkspacesWorkspaceSlugLabsPlaygroundRoute
  '/workspaces/$workspaceSlug/products/$productId': typeof AuthenticatedWorkspacesWorkspaceSlugProductsProductIdRoute
  '/workspaces/$workspaceSlug/inbox': typeof AuthenticatedWorkspacesWorkspaceSlugInboxIndexRoute
  '/workspaces/$workspaceSlug/product-visuals-v2': typeof AuthenticatedWorkspacesWorkspaceSlugProductVisualsV2IndexRoute
  '/workspaces/$workspaceSlug/products': typeof AuthenticatedWorkspacesWorkspaceSlugProductsIndexRoute
  '/workspaces/$workspaceSlug/styles': typeof AuthenticatedWorkspacesWorkspaceSlugStylesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/workspaces': typeof AuthenticatedWorkspacesRouteRouteWithChildren
  '/_authenticated/workspaces/$workspaceSlug': typeof AuthenticatedWorkspacesWorkspaceSlugRouteRouteWithChildren
  '/_authenticated/workspaces/': typeof AuthenticatedWorkspacesIndexRoute
  '/_authenticated/workspaces/$workspaceSlug/labs': typeof AuthenticatedWorkspacesWorkspaceSlugLabsRouteRouteWithChildren
  '/_authenticated/workspaces/$workspaceSlug/calendar': typeof AuthenticatedWorkspacesWorkspaceSlugCalendarRoute
  '/_authenticated/workspaces/$workspaceSlug/composer': typeof AuthenticatedWorkspacesWorkspaceSlugComposerRoute
  '/_authenticated/workspaces/$workspaceSlug/content': typeof AuthenticatedWorkspacesWorkspaceSlugContentRoute
  '/_authenticated/workspaces/$workspaceSlug/inbox': typeof AuthenticatedWorkspacesWorkspaceSlugInboxRouteWithChildren
  '/_authenticated/workspaces/$workspaceSlug/insights': typeof AuthenticatedWorkspacesWorkspaceSlugInsightsRoute
  '/_authenticated/workspaces/$workspaceSlug/product-visuals': typeof AuthenticatedWorkspacesWorkspaceSlugProductVisualsRoute
  '/_authenticated/workspaces/$workspaceSlug/settings': typeof AuthenticatedWorkspacesWorkspaceSlugSettingsRoute
  '/_authenticated/workspaces/$workspaceSlug/team': typeof AuthenticatedWorkspacesWorkspaceSlugTeamRoute
  '/_authenticated/workspaces/$workspaceSlug/': typeof AuthenticatedWorkspacesWorkspaceSlugIndexRoute
  '/_authenticated/workspaces/$workspaceSlug/inbox/$conversationId': typeof AuthenticatedWorkspacesWorkspaceSlugInboxConversationIdRoute
  '/_authenticated/workspaces/$workspaceSlug/labs/api-testing': typeof AuthenticatedWorkspacesWorkspaceSlugLabsApiTestingRoute
  '/_authenticated/workspaces/$workspaceSlug/labs/playground': typeof AuthenticatedWorkspacesWorkspaceSlugLabsPlaygroundRoute
  '/_authenticated/workspaces/$workspaceSlug/products/$productId': typeof AuthenticatedWorkspacesWorkspaceSlugProductsProductIdRoute
  '/_authenticated/workspaces/$workspaceSlug/inbox/': typeof AuthenticatedWorkspacesWorkspaceSlugInboxIndexRoute
  '/_authenticated/workspaces/$workspaceSlug/product-visuals-v2/': typeof AuthenticatedWorkspacesWorkspaceSlugProductVisualsV2IndexRoute
  '/_authenticated/workspaces/$workspaceSlug/products/': typeof AuthenticatedWorkspacesWorkspaceSlugProductsIndexRoute
  '/_authenticated/workspaces/$workspaceSlug/styles/': typeof AuthenticatedWorkspacesWorkspaceSlugStylesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/workspaces'
    | '/workspaces/$workspaceSlug'
    | '/workspaces/'
    | '/workspaces/$workspaceSlug/labs'
    | '/workspaces/$workspaceSlug/calendar'
    | '/workspaces/$workspaceSlug/composer'
    | '/workspaces/$workspaceSlug/content'
    | '/workspaces/$workspaceSlug/inbox'
    | '/workspaces/$workspaceSlug/insights'
    | '/workspaces/$workspaceSlug/product-visuals'
    | '/workspaces/$workspaceSlug/settings'
    | '/workspaces/$workspaceSlug/team'
    | '/workspaces/$workspaceSlug/'
    | '/workspaces/$workspaceSlug/inbox/$conversationId'
    | '/workspaces/$workspaceSlug/labs/api-testing'
    | '/workspaces/$workspaceSlug/labs/playground'
    | '/workspaces/$workspaceSlug/products/$productId'
    | '/workspaces/$workspaceSlug/inbox/'
    | '/workspaces/$workspaceSlug/product-visuals-v2'
    | '/workspaces/$workspaceSlug/products'
    | '/workspaces/$workspaceSlug/styles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/workspaces'
    | '/workspaces/$workspaceSlug/labs'
    | '/workspaces/$workspaceSlug/calendar'
    | '/workspaces/$workspaceSlug/composer'
    | '/workspaces/$workspaceSlug/content'
    | '/workspaces/$workspaceSlug/insights'
    | '/workspaces/$workspaceSlug/product-visuals'
    | '/workspaces/$workspaceSlug/settings'
    | '/workspaces/$workspaceSlug/team'
    | '/workspaces/$workspaceSlug'
    | '/workspaces/$workspaceSlug/inbox/$conversationId'
    | '/workspaces/$workspaceSlug/labs/api-testing'
    | '/workspaces/$workspaceSlug/labs/playground'
    | '/workspaces/$workspaceSlug/products/$productId'
    | '/workspaces/$workspaceSlug/inbox'
    | '/workspaces/$workspaceSlug/product-visuals-v2'
    | '/workspaces/$workspaceSlug/products'
    | '/workspaces/$workspaceSlug/styles'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/workspaces'
    | '/_authenticated/workspaces/$workspaceSlug'
    | '/_authenticated/workspaces/'
    | '/_authenticated/workspaces/$workspaceSlug/labs'
    | '/_authenticated/workspaces/$workspaceSlug/calendar'
    | '/_authenticated/workspaces/$workspaceSlug/composer'
    | '/_authenticated/workspaces/$workspaceSlug/content'
    | '/_authenticated/workspaces/$workspaceSlug/inbox'
    | '/_authenticated/workspaces/$workspaceSlug/insights'
    | '/_authenticated/workspaces/$workspaceSlug/product-visuals'
    | '/_authenticated/workspaces/$workspaceSlug/settings'
    | '/_authenticated/workspaces/$workspaceSlug/team'
    | '/_authenticated/workspaces/$workspaceSlug/'
    | '/_authenticated/workspaces/$workspaceSlug/inbox/$conversationId'
    | '/_authenticated/workspaces/$workspaceSlug/labs/api-testing'
    | '/_authenticated/workspaces/$workspaceSlug/labs/playground'
    | '/_authenticated/workspaces/$workspaceSlug/products/$productId'
    | '/_authenticated/workspaces/$workspaceSlug/inbox/'
    | '/_authenticated/workspaces/$workspaceSlug/product-visuals-v2/'
    | '/_authenticated/workspaces/$workspaceSlug/products/'
    | '/_authenticated/workspaces/$workspaceSlug/styles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspaces': {
      id: '/_authenticated/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AuthenticatedWorkspacesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspaces/': {
      id: '/_authenticated/workspaces/'
      path: '/'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof AuthenticatedWorkspacesIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug': {
      id: '/_authenticated/workspaces/$workspaceSlug'
      path: '/$workspaceSlug'
      fullPath: '/workspaces/$workspaceSlug'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRouteImport
      parentRoute: typeof AuthenticatedWorkspacesRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/': {
      id: '/_authenticated/workspaces/$workspaceSlug/'
      path: '/'
      fullPath: '/workspaces/$workspaceSlug/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/team': {
      id: '/_authenticated/workspaces/$workspaceSlug/team'
      path: '/team'
      fullPath: '/workspaces/$workspaceSlug/team'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugTeamRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/settings': {
      id: '/_authenticated/workspaces/$workspaceSlug/settings'
      path: '/settings'
      fullPath: '/workspaces/$workspaceSlug/settings'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugSettingsRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/product-visuals': {
      id: '/_authenticated/workspaces/$workspaceSlug/product-visuals'
      path: '/product-visuals'
      fullPath: '/workspaces/$workspaceSlug/product-visuals'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugProductVisualsRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/insights': {
      id: '/_authenticated/workspaces/$workspaceSlug/insights'
      path: '/insights'
      fullPath: '/workspaces/$workspaceSlug/insights'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugInsightsRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/inbox': {
      id: '/_authenticated/workspaces/$workspaceSlug/inbox'
      path: '/inbox'
      fullPath: '/workspaces/$workspaceSlug/inbox'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugInboxRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/content': {
      id: '/_authenticated/workspaces/$workspaceSlug/content'
      path: '/content'
      fullPath: '/workspaces/$workspaceSlug/content'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugContentRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/composer': {
      id: '/_authenticated/workspaces/$workspaceSlug/composer'
      path: '/composer'
      fullPath: '/workspaces/$workspaceSlug/composer'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugComposerRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/calendar': {
      id: '/_authenticated/workspaces/$workspaceSlug/calendar'
      path: '/calendar'
      fullPath: '/workspaces/$workspaceSlug/calendar'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugCalendarRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/labs': {
      id: '/_authenticated/workspaces/$workspaceSlug/labs'
      path: '/labs'
      fullPath: '/workspaces/$workspaceSlug/labs'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugLabsRouteRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/styles/': {
      id: '/_authenticated/workspaces/$workspaceSlug/styles/'
      path: '/styles'
      fullPath: '/workspaces/$workspaceSlug/styles'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugStylesIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/products/': {
      id: '/_authenticated/workspaces/$workspaceSlug/products/'
      path: '/products'
      fullPath: '/workspaces/$workspaceSlug/products'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugProductsIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/product-visuals-v2/': {
      id: '/_authenticated/workspaces/$workspaceSlug/product-visuals-v2/'
      path: '/product-visuals-v2'
      fullPath: '/workspaces/$workspaceSlug/product-visuals-v2'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugProductVisualsV2IndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/inbox/': {
      id: '/_authenticated/workspaces/$workspaceSlug/inbox/'
      path: '/'
      fullPath: '/workspaces/$workspaceSlug/inbox/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugInboxIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugInboxRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/products/$productId': {
      id: '/_authenticated/workspaces/$workspaceSlug/products/$productId'
      path: '/products/$productId'
      fullPath: '/workspaces/$workspaceSlug/products/$productId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugProductsProductIdRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/labs/playground': {
      id: '/_authenticated/workspaces/$workspaceSlug/labs/playground'
      path: '/playground'
      fullPath: '/workspaces/$workspaceSlug/labs/playground'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugLabsPlaygroundRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugLabsRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/labs/api-testing': {
      id: '/_authenticated/workspaces/$workspaceSlug/labs/api-testing'
      path: '/api-testing'
      fullPath: '/workspaces/$workspaceSlug/labs/api-testing'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugLabsApiTestingRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugLabsRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/inbox/$conversationId': {
      id: '/_authenticated/workspaces/$workspaceSlug/inbox/$conversationId'
      path: '/$conversationId'
      fullPath: '/workspaces/$workspaceSlug/inbox/$conversationId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugInboxConversationIdRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugInboxRoute
    }
  }
}

interface AuthenticatedWorkspacesWorkspaceSlugLabsRouteRouteChildren {
  AuthenticatedWorkspacesWorkspaceSlugLabsApiTestingRoute: typeof AuthenticatedWorkspacesWorkspaceSlugLabsApiTestingRoute
  AuthenticatedWorkspacesWorkspaceSlugLabsPlaygroundRoute: typeof AuthenticatedWorkspacesWorkspaceSlugLabsPlaygroundRoute
}

const AuthenticatedWorkspacesWorkspaceSlugLabsRouteRouteChildren: AuthenticatedWorkspacesWorkspaceSlugLabsRouteRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceSlugLabsApiTestingRoute:
      AuthenticatedWorkspacesWorkspaceSlugLabsApiTestingRoute,
    AuthenticatedWorkspacesWorkspaceSlugLabsPlaygroundRoute:
      AuthenticatedWorkspacesWorkspaceSlugLabsPlaygroundRoute,
  }

const AuthenticatedWorkspacesWorkspaceSlugLabsRouteRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceSlugLabsRouteRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceSlugLabsRouteRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceSlugInboxRouteChildren {
  AuthenticatedWorkspacesWorkspaceSlugInboxConversationIdRoute: typeof AuthenticatedWorkspacesWorkspaceSlugInboxConversationIdRoute
  AuthenticatedWorkspacesWorkspaceSlugInboxIndexRoute: typeof AuthenticatedWorkspacesWorkspaceSlugInboxIndexRoute
}

const AuthenticatedWorkspacesWorkspaceSlugInboxRouteChildren: AuthenticatedWorkspacesWorkspaceSlugInboxRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceSlugInboxConversationIdRoute:
      AuthenticatedWorkspacesWorkspaceSlugInboxConversationIdRoute,
    AuthenticatedWorkspacesWorkspaceSlugInboxIndexRoute:
      AuthenticatedWorkspacesWorkspaceSlugInboxIndexRoute,
  }

const AuthenticatedWorkspacesWorkspaceSlugInboxRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceSlugInboxRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceSlugInboxRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceSlugRouteRouteChildren {
  AuthenticatedWorkspacesWorkspaceSlugLabsRouteRoute: typeof AuthenticatedWorkspacesWorkspaceSlugLabsRouteRouteWithChildren
  AuthenticatedWorkspacesWorkspaceSlugCalendarRoute: typeof AuthenticatedWorkspacesWorkspaceSlugCalendarRoute
  AuthenticatedWorkspacesWorkspaceSlugComposerRoute: typeof AuthenticatedWorkspacesWorkspaceSlugComposerRoute
  AuthenticatedWorkspacesWorkspaceSlugContentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugContentRoute
  AuthenticatedWorkspacesWorkspaceSlugInboxRoute: typeof AuthenticatedWorkspacesWorkspaceSlugInboxRouteWithChildren
  AuthenticatedWorkspacesWorkspaceSlugInsightsRoute: typeof AuthenticatedWorkspacesWorkspaceSlugInsightsRoute
  AuthenticatedWorkspacesWorkspaceSlugProductVisualsRoute: typeof AuthenticatedWorkspacesWorkspaceSlugProductVisualsRoute
  AuthenticatedWorkspacesWorkspaceSlugSettingsRoute: typeof AuthenticatedWorkspacesWorkspaceSlugSettingsRoute
  AuthenticatedWorkspacesWorkspaceSlugTeamRoute: typeof AuthenticatedWorkspacesWorkspaceSlugTeamRoute
  AuthenticatedWorkspacesWorkspaceSlugIndexRoute: typeof AuthenticatedWorkspacesWorkspaceSlugIndexRoute
  AuthenticatedWorkspacesWorkspaceSlugProductsProductIdRoute: typeof AuthenticatedWorkspacesWorkspaceSlugProductsProductIdRoute
  AuthenticatedWorkspacesWorkspaceSlugProductVisualsV2IndexRoute: typeof AuthenticatedWorkspacesWorkspaceSlugProductVisualsV2IndexRoute
  AuthenticatedWorkspacesWorkspaceSlugProductsIndexRoute: typeof AuthenticatedWorkspacesWorkspaceSlugProductsIndexRoute
  AuthenticatedWorkspacesWorkspaceSlugStylesIndexRoute: typeof AuthenticatedWorkspacesWorkspaceSlugStylesIndexRoute
}

const AuthenticatedWorkspacesWorkspaceSlugRouteRouteChildren: AuthenticatedWorkspacesWorkspaceSlugRouteRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceSlugLabsRouteRoute:
      AuthenticatedWorkspacesWorkspaceSlugLabsRouteRouteWithChildren,
    AuthenticatedWorkspacesWorkspaceSlugCalendarRoute:
      AuthenticatedWorkspacesWorkspaceSlugCalendarRoute,
    AuthenticatedWorkspacesWorkspaceSlugComposerRoute:
      AuthenticatedWorkspacesWorkspaceSlugComposerRoute,
    AuthenticatedWorkspacesWorkspaceSlugContentRoute:
      AuthenticatedWorkspacesWorkspaceSlugContentRoute,
    AuthenticatedWorkspacesWorkspaceSlugInboxRoute:
      AuthenticatedWorkspacesWorkspaceSlugInboxRouteWithChildren,
    AuthenticatedWorkspacesWorkspaceSlugInsightsRoute:
      AuthenticatedWorkspacesWorkspaceSlugInsightsRoute,
    AuthenticatedWorkspacesWorkspaceSlugProductVisualsRoute:
      AuthenticatedWorkspacesWorkspaceSlugProductVisualsRoute,
    AuthenticatedWorkspacesWorkspaceSlugSettingsRoute:
      AuthenticatedWorkspacesWorkspaceSlugSettingsRoute,
    AuthenticatedWorkspacesWorkspaceSlugTeamRoute:
      AuthenticatedWorkspacesWorkspaceSlugTeamRoute,
    AuthenticatedWorkspacesWorkspaceSlugIndexRoute:
      AuthenticatedWorkspacesWorkspaceSlugIndexRoute,
    AuthenticatedWorkspacesWorkspaceSlugProductsProductIdRoute:
      AuthenticatedWorkspacesWorkspaceSlugProductsProductIdRoute,
    AuthenticatedWorkspacesWorkspaceSlugProductVisualsV2IndexRoute:
      AuthenticatedWorkspacesWorkspaceSlugProductVisualsV2IndexRoute,
    AuthenticatedWorkspacesWorkspaceSlugProductsIndexRoute:
      AuthenticatedWorkspacesWorkspaceSlugProductsIndexRoute,
    AuthenticatedWorkspacesWorkspaceSlugStylesIndexRoute:
      AuthenticatedWorkspacesWorkspaceSlugStylesIndexRoute,
  }

const AuthenticatedWorkspacesWorkspaceSlugRouteRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceSlugRouteRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceSlugRouteRouteChildren,
  )

interface AuthenticatedWorkspacesRouteRouteChildren {
  AuthenticatedWorkspacesWorkspaceSlugRouteRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRouteWithChildren
  AuthenticatedWorkspacesIndexRoute: typeof AuthenticatedWorkspacesIndexRoute
}

const AuthenticatedWorkspacesRouteRouteChildren: AuthenticatedWorkspacesRouteRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceSlugRouteRoute:
      AuthenticatedWorkspacesWorkspaceSlugRouteRouteWithChildren,
    AuthenticatedWorkspacesIndexRoute: AuthenticatedWorkspacesIndexRoute,
  }

const AuthenticatedWorkspacesRouteRouteWithChildren =
  AuthenticatedWorkspacesRouteRoute._addFileChildren(
    AuthenticatedWorkspacesRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedWorkspacesRouteRoute: typeof AuthenticatedWorkspacesRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedWorkspacesRouteRoute:
    AuthenticatedWorkspacesRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
