name: Deployment

on:
  push:
    branches:
      - dev
      - production

concurrency: 
  group: ${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/cache@v4
        with:
          path: |
            .sst
          key: ${{ runner.os }}-sst

      - uses: pnpm/action-setup@v2
        with:
          version: 10.14.0

      - uses: actions/setup-node@v1
        with:
          node-version: "20"

      - run: "curl -fsSL https://ion.sst.dev/install | bash"

      - if: github.ref == 'refs/heads/dev'
        name: Configure Dev AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::549182891830:role/openpromo-dev-github
          aws-region: us-east-1

      - if: github.ref == 'refs/heads/production'
        name: Configure Production AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::549182891830:role/openpromo-production-github
          aws-region: us-east-1

      - name: deps
        run: |
          curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh || wget -t 3 -qO- https://cli.doppler.com/install.sh | sudo sh
          pnpm install --frozen-lockfile

      - name: typecheck
        run: pnpm check

      - name: Deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          # STRIPE_API_KEY: ${{ github.ref == 'refs/heads/production' && secrets.PRODUCTION_STRIPE_API_KEY || secrets.DEV_STRIPE_API_KEY }}
          PLANETSCALE_SERVICE_TOKEN_NAME: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_NAME }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
          PLANETSCALE_SERVICE_TOKEN_ID: ${{secrets.PLANETSCALE_SERVICE_TOKEN_ID}}

        run: |
          pnpm sst install
          pnpm sst deploy --stage=${GITHUB_REF_NAME}