name: Code Quality

on:
  push:
  pull_request:

jobs:
  biome-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2

      - name: Biome check
        run: biome ci --diagnostic-level=warn

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Install sst providers
        run: pnpm exec sst install

      - name: typecheck
        run: pnpm -r typecheck
