name: Code Quality

on:
  push:
    branches:
      - staging
      - production
  pull_request:

permissions:
  contents: read

jobs:
  biome-check:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2

      - name: Biome check
        run: biome ci --diagnostic-level=warn

  typecheck:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: typecheck
        run: pnpm run typecheck
