name: Deployment

on:
  push:
    branches:
      - dev
      - production

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - if: github.ref == 'refs/heads/dev'
        name: Configure Dev AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::549182891830:role/openpromo-dev-github
          aws-region: us-east-1

      - if: github.ref == 'refs/heads/production'
        name: Configure Production AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::549182891830:role/openpromo-production-github
          aws-region: us-east-1

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v3


      - name: Wait for biome check
        uses: fountainhead/action-wait-for-check@v1.2.0
        id: biome-check
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: biome-check

      - name: Wait for typecheck
        uses: fountainhead/action-wait-for-check@v1.2.0
        id: typecheck
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: typecheck

      - name: Exit if code quality checks failed
        if: steps.biome-check.outputs.conclusion != 'success' || steps.typecheck.outputs.conclusion != 'success'
        run: |
          echo "Code quality checks failed"
          exit 1

      - name: Deploy
        id: deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          # STRIPE_API_KEY: ${{ github.ref == 'refs/heads/production' && secrets.PRODUCTION_STRIPE_API_KEY || secrets.DEV_STRIPE_API_KEY }}
          PLANETSCALE_SERVICE_TOKEN_NAME: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_NAME }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
          PLANETSCALE_SERVICE_TOKEN_ID: ${{secrets.PLANETSCALE_SERVICE_TOKEN_ID}}
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
          SST_STAGE: ${{ github.ref == 'refs/heads/production' && 'production' || 'dev' }}
        run: |
          pnpm sst install
          pnpm sync_secrets
          pnpm sst deploy --stage=${GITHUB_REF_NAME}

      - name: Send success notification to Discord
        if: success()
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{ secrets.DISCORD_DEPLOYMENT_WEBHOOK_URL }}
          message: |
            **[Success] Openpromo Deployed**
            - **Branch:** `${{ github.ref_name }}`
            - **Commit:** [${{ github.event.head_commit.message }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}) (`${{ github.sha }}`)

      - name: Send failure notification to Discord
        if: failure()
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{ secrets.DISCORD_DEPLOYMENT_WEBHOOK_URL }}
          message: |
            **[Failed] Openpromo Deployment Failed** ❌
            - **Branch:** `${{ github.ref_name }}`
            - **Commit:** [${{ github.event.head_commit.message }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}) (`${{ github.sha }}`)
            - **Job:** [${{ github.job }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            - **Error:** Check the workflow logs for details
